### ISSUE TITLE
Dictionary for parameters in yaml file 

### ISSUE THREAD

**Issue by Christophe-pere** [mlflow/recipes-classification-template#29]
Hi,

I'm trying to use a dictionary to pass a set of parameters in the `ingestion.py` file using the `yaml` file.  

I use the code below:

```
steps:
  # Specifies the dataset to use for model development
  ingest: 
      using: "custom"
      location: "../dataset.csv"
      loader_method: read_csv_as_dataframe 
      ingest_params:
          - label: 'fraud_bool'
          - train_sample: 400
          - validation_sample: 200
          - test_sample: 200
``` 
In the `ingestion.py` file, I modified the function to: 

```
def read_csv_as_dataframe(location: str, ingest_params: Dict[str, Any]) -> DataFrame
```

When I plot the dictionary, the output gives me `custom` and not the dict. 

 The objective is to use the `yaml` file to add flexibility to the pipeline.

How to do that?
